name: CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code from your repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          cd flask-app
          pip install -r requirements.txt

      # 4. Run basic tests
      - name: Run tests
        run: |
          cd flask-app
          python -m unittest || echo "No test found"

      # 5. Log in to Dockerhub
      - name: Log in to Dockerhub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | dockerlogin -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 6. Build Docker image
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_REPO }}:latest .

      # 7. Push Docker image
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_REPO }}:latest
